import { test, expect } from "@playwright/test";

/**
 * Open Graph / social-preview regression suite.
 *
 * The share thumbnail (LinkedIn, Facebook, X) is generated by
 * app/opengraph-image.tsx and auto-wired into <head> via metadataBase. These
 * checks guard the contract crawlers depend on: a declared 1200x630 PNG whose
 * URL actually serves a non-empty image. A broken image route is the usual
 * cause of a blank LinkedIn card, so we fetch it, not just read the tag.
 */

const content = (page: import("@playwright/test").Page, selector: string) =>
  page.locator(selector).getAttribute("content");

test.describe("open graph image", () => {
  test("declares a 1200x630 PNG og:image", async ({ page }) => {
    await page.goto("/");

    await expect(page.locator('meta[property="og:image:width"]')).toHaveAttribute(
      "content",
      "1200",
    );
    await expect(
      page.locator('meta[property="og:image:height"]'),
    ).toHaveAttribute("content", "630");
    await expect(
      page.locator('meta[property="og:image:type"]'),
    ).toHaveAttribute("content", "image/png");

    const ogImage = await content(page, 'meta[property="og:image"]');
    expect(ogImage, "og:image content present").toBeTruthy();
  });

  test("twitter card mirrors the og:image", async ({ page }) => {
    await page.goto("/");
    await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
      "content",
      "summary_large_image",
    );
    const twitterImage = await content(page, 'meta[name="twitter:image"]');
    expect(twitterImage, "twitter:image content present").toBeTruthy();
  });

  test("og:image URL serves a non-empty PNG", async ({ page, request }) => {
    await page.goto("/");
    const ogImage = await content(page, 'meta[property="og:image"]');
    expect(ogImage).toBeTruthy();

    // Resolve relative/absolute against the page origin so the test works
    // against any baseURL (dev, prod build, or PLAYWRIGHT_BASE_URL).
    const url = new URL(ogImage!, page.url()).toString();
    const res = await request.get(url);
    expect(res.status(), `GET ${url}`).toBe(200);
    expect(res.headers()["content-type"]).toContain("image/png");
    const body = await res.body();
    expect(body.byteLength, "image body is non-empty").toBeGreaterThan(1000);
  });
});
